# Generated by Django 4.2.4 on 2023-08-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_ammount',
            new_name='total_amount',
        ),
    ]
